# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Specify additional command line arguments
#
- arguments:
  - "-XAllowAmbiguousTypes"
  - "-XBangPatterns"
  - "-XConstraintKinds"
  - "-XDataKinds"
  - "-XDeriveGeneric"
  - "-XDerivingStrategies"
  - "-XDerivingVia"
  - "-XEmptyCase"
  - "-XExplicitNamespaces"
  - "-XFlexibleContexts"
  - "-XFlexibleInstances"
  - "-XFunctionalDependencies"
  - "-XGADTs"
  - "-XGeneralizedNewtypeDeriving"
  - "-XImportQualifiedPost"
  - "-XInstanceSigs"
  - "-XKindSignatures"
  - "-XLambdaCase"
  - "-XMultiParamTypeClasses"
  - "-XNoStarIsType"
  - "-XPatternSynonyms"
  - "-XOverloadedStrings"
  - "-XPolyKinds"
  - "-XQuasiQuotes"
  - "-XRankNTypes"
  - "-XRoleAnnotations"
  - "-XScopedTypeVariables"
  - "-XStandaloneDeriving"
  - "-XTypeApplications"
  - "-XTypeFamilies"
  - "-XTypeOperators"
  - "-XTypeSynonymInstances"
  - "-XUndecidableInstances"
  - "-XViewPatterns"


# Control which extensions/flags/modules/functions can be used
#
- extensions:
#   - default: false # all extension are banned by default
  - name:
    - AllowAmbiguousTypes
    - BangPatterns
    - ConstraintKinds
    - DataKinds
    - DeriveGeneric
    - DerivingStrategies
    - DerivingVia
    - EmptyCase
    - ExplicitNamespaces
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - ImportQualifiedPost
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - NoStarIsType
    - OverloadedStrings
    - PolyKinds
    - QuasiQuotes
    - RankNTypes
    - RoleAnnotations
    - ScopedTypeVariables
    - StandaloneDeriving
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - TypeSynonymInstances
    - UndecidableInstances
    - ViewPatterns


# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

# The hints are named by the string they display in warning messages.
# For example, if you see a warning starting like
#
# Main.hs:116:51: Warning: Redundant ==
#
# You can refer to that hint with `{name: Redundant ==}` (see below).

# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# - group: {name: generalise, enabled: true}
#
# Warn on use of partial functions
# - group: {name: partial, enabled: true}


# Ignore some builtin hints
- ignore: {name: Use list comprehension}
- ignore: {name: Avoid lambda using `infix`}
- ignore: {name: Use map with tuple-section}
- ignore: {name: Use tuple-section}
- ignore: {name: Use first}
- ignore : {name: Use camelCase}
- ignore: {name: Avoid restricted extensions, within: Main}
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules


# Define some custom infix operators
# - fixity: infixr 3 ~^#^~


# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
